services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
    - ./otel/:/usr/src/myapp
    - ./otel/.cargo/registry:/home/php-rust/.cargo/registry
    - ./otel/.cargo/git:/home/php-rust/.cargo/git
    user: php-rust
  collector:
    image: otel/opentelemetry-collector-contrib
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./files/collector/otel-collector-config.yml:/etc/otel-collector-config.yml
