services:
  php:
    build:
      context: .
    volumes:
    - ./otel/:/usr/src/myapp
    - ./.cargo/registry:/home/php-rust/.cargo/registry
    user: php-rust
  collector:
    image: otel/opentelemetry-collector-contrib
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./files/collector/otel-collector-config.yml:/etc/otel-collector-config.yml