[package]
name = "otel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
phper = "0.14.1"
opentelemetry = "0.27.1"
opentelemetry-stdout = "0.27.0"
opentelemetry_sdk = "0.27.1"
