[package]
name = "otel"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "otel"
crate-type = ["cdylib"]

[dependencies]
phper = "0.14.1"
opentelemetry = "0.28.0"
opentelemetry-stdout = "0.28.0"
opentelemetry_sdk = "0.28.0"
tokio = { version = "1.0", features = ["full"] }
once_cell = "1.20.3"

[dev-dependencies]
phper-test = "0.14.1"
